import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";

const roboto400 = Roboto({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-roboto-400",
});
const roboto700 = Roboto({
  weight: "700",
  subsets: ["latin"],
  variable: "--font-roboto-700",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={` antialised ${roboto400.variable} ${roboto700.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
